import os

def detect_dns_config():

    dns_info = {
        "manager": "Unknown",
        "local_resolvers": [],
        "real_servers": []
    }

    resolv_path = "/etc/resolv.conf"

    if not os.path.exists(resolv_path):
        print("File /etc/resolv.conf not found")
        return dns_info
    
    if os.path.islink(resolv_path):
        target_path = os.readlink(resolv_path)

        if "systemd-resolved" in target_path:
            dns_info["manager"] = "systemd-resolved"
        elif "NetworkManager" in target_path:
            dns_info["manager"] = "NetworkManager"

    with open(resolv_path, "r") as file:
        for line in file:
            if "Generated by NetworkManager" in line:
                dns_info["manager"] = "NetworkManager"
            elif "systemd-resolved" in line:
                dns_info["manager"] = "systemd-resolved"
                
            if line.strip().startswith("#") or not line.strip():
                continue

            if line.startswith("nameserver"):
                ip = line.split()[1]
                dns_info["local_resolvers"].append(ip)

    if "127.0.0.53" in dns_info["local_resolvers"]:
        dns_info["manager"] = "systemd-resolved"

        real_resolv_path = "/run/systemd/resolve/resolv.conf"
        if os.path.exists(real_resolv_path):
            with open(real_resolv_path, "r") as file:
                for line in file:
                    if line.strip().startswith("#") or not line.strip():
                        continue
                    
                    if line.startswith("nameserver"):
                        ip = line.split()[1]
                        dns_info["real_servers"].append(ip)
        else:
            dns_info["real_servers"] = dns_info["local_resolvers"].copy()
        
    return dns_info

if __name__ == "__main__":
    print("Starting DNS lookup")
    res = detect_dns_config()

    print(f"DNS managers: {res['manager']}")
    print(f"Local resolvers (Stub): {res['local_resolvers']}")
    print(f"Real DNS Servers (Upstream): {res['real_servers']}")